<a href="https://colab.research.google.com/github/Anthonylwz/cssma/blob/main/ejercicios%20propuestos%201%20y%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, libreria de ciencia de datos

In [ ]:
import numpy as np
#pip install numpy

array de 1 dimension

In [ ]:
array_1d=np.array((10,20,30))
print(array_1d)

[10 20 30]


In [ ]:
array_1d

array([10, 20, 30])

Array de 2 dimensiones


In [ ]:
array_2d=np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

Array de 3 dimensiones

In [ ]:
array_3d=np.array([(10,30,40),(50,60,70),(80,90,100)], dtype =float)
array_3d

array([[ 10.,  30.,  40.],
       [ 50.,  60.,  70.],
       [ 80.,  90., 100.]])

Array con cerors de 3 filas y columnas


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Array de unos y con 2 dimensiones 4 filas y 5 columnas

In [ ]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

Arrays intervalos y saltos

In [ ]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

Array con intervalos y divisiones


In [ ]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

Arrays con valores dados

números primos 11 al 30

In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Array con matriz identidad, diagonal de unos

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array valores Aletorios

In [ ]:
np.random.random((5,4))

array([[0.22427513, 0.8185829 , 0.59601325, 0.17335236],
       [0.53132843, 0.84154778, 0.60544078, 0.77270054],
       [0.27896458, 0.57092147, 0.69575195, 0.13880172],
       [0.83260906, 0.12338563, 0.31662342, 0.36102589],
       [0.24371596, 0.07196885, 0.16905481, 0.55747915]])

Array de numeros vacios 4/*3

In [ ]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Grabar y cargar

In [ ]:
#Grabar
np.save("mi_array_3d",array_3d)

In [ ]:
#Cargar
mi_array=np.load("mi_array_3d.npy")
mi_array

array([[ 10.,  30.,  40.],
       [ 50.,  60.,  70.],
       [ 80.,  90., 100.]])

In [ ]:
#Grabar
np.save("array_2d", array_2d)

In [ ]:
#Cargar
mi_array=np.load("array_2d.npy")
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

Grabar y cargar ficheros de texto

In [ ]:
#grabar el fichero de texto
np.savetxt("mi_array.txt",array_2d, delimiter=",")

In [ ]:
#cargar de fichero de texto
np.loadtxt("mi_array.txt", delimiter=",")

array([[10., 20., 30.],
       [50., 60., 70.]])

ejercicio01

In [ ]:
#grabar
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios/ejercicio 01.npy", asignaturas)

In [ ]:
#cargar
np.load("ejercicios/ejercicio 01.npy")

array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'],
      dtype='<U11')

ejercicio 02

In [ ]:
materias = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios/ejercicio02.npy", materias)

In [ ]:
np.load("ejercicios/ejercicio02.npy")
for m in materias:
    print(f"Yo estudio {m}")

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


ejercicio 03

In [ ]:
#grabar
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios/ejercicio_03.npy", asignaturas)

In [ ]:
112#cargar
asignaturas = np.load("ejercicios/ejercicio_03.npy")
for asignatura in asignaturas:
    nota = input(f"¿Qué nota sacaste en {asignatura}? ")
    print(f"En {asignatura} has sacado {nota}")


¿Qué nota sacaste en Matemáticas? 12
En Matemáticas has sacado 12
¿Qué nota sacaste en Física? 12
En Física has sacado 12
¿Qué nota sacaste en Química? 12
En Química has sacado 12
¿Qué nota sacaste en Historia? 12
En Historia has sacado 12
¿Qué nota sacaste en Lengua? 12
En Lengua has sacado 12


Ejercicio 04

In [ ]:
#grabar
import numpy as np
ganadores = []
for i in range(6):
    numero = int(input(f"Introduce el número ganador {i+1}: "))
    ganadores.append(numero)
np.save("ejercicios/ejercicio_04.npy", np.array(ganadores))



Introduce el número ganador 1: 12
Introduce el número ganador 2: 12
Introduce el número ganador 3: 12
Introduce el número ganador 4: 12
Introduce el número ganador 5: 12
Introduce el número ganador 6: 12


In [ ]:
#cargar
import numpy as np
ganadores = np.load("ejercicios/ejercicio_04.npy")
ganadores_ordenados = np.sort(ganadores)
print("Números ganadores ordenados:", ", ".join(str(n) for n in ganadores_ordenados))


Números ganadores ordenados: 12, 12, 12, 12, 12, 12


Ejercicio 05

In [ ]:
#  grabar
import numpy as np

numeros = list(range(1, 11))
np.save("ejercicios/ejercicio_05.npy", numeros)


In [ ]:
#  cargar
import numpy as np
numeros = np.load("ejercicios/ejercicio_05.npy")
print("Números en orden inverso:")
print(", ".join(str(n) for n in reversed(numeros)))


Números en orden inverso:
10, 9, 8, 7, 6, 5, 4, 3, 2, 1


Ejercicio 06

In [ ]:
# grabar
import numpy as np
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios/ejercicio_06.npy", asignaturas)


In [ ]:
# cargar
import numpy as np
asignaturas = np.load("ejercicios/ejercicio_06.npy")
suspendidas = []
for asignatura in asignaturas:
    nota = float(input(f"¿Qué nota sacaste en {asignatura}? "))
    if nota < 5:
        suspendidas.append(asignatura)
print("Tienes que repetir:", ", ".join(suspendidas))


¿Qué nota sacaste en Matemáticas? 12
¿Qué nota sacaste en Física? 12
¿Qué nota sacaste en Química? 12
¿Qué nota sacaste en Historia? 12
¿Qué nota sacaste en Lengua? 12
Tienes que repetir: 


Ejercicio 07

In [ ]:
# grabar
import numpy as np
import string

abecedario = list(string.ascii_lowercase)
np.save("ejercicios/ejercicio_07.npy", np.array(abecedario))


In [ ]:
# 📤 cargar
import numpy as np

abecedario = np.load("ejercicios/ejercicio_07.npy")

resultado = [letra for i, letra in enumerate(abecedario) if (i + 1) % 3 != 0]

print(", ".join(resultado))


a, b, d, e, g, h, j, k, m, n, p, q, s, t, v, w, y, z


Ejercicio 8

In [ ]:
# grabar
import numpy as np

palabra = input("Introduce una palabra: ")
np.save("ejercicios/ejercicio_08.npy", np.array([palabra]))


Introduce una palabra: hola


In [ ]:
# 📤 cargar
import numpy as np

palabra = np.load("ejercicios/ejercicio_08.npy")[0]

if palabra == palabra[::-1]:
    print("La palabra es un palíndromo.")
else:
    print("La palabra no es un palíndromo.")


La palabra no es un palíndromo.


Ejercicio 9

In [ ]:
# grabar
import numpy as np

palabra = input("Introduce una palabra: ").lower()
np.save("ejercicios/ejercicio_09.npy", np.array([palabra]))


Introduce una palabra: love


In [ ]:
# cargar
import numpy as np
palabra = np.load("ejercicios/ejercicio_09.npy")[0]
vocales = "aeiou"
for vocal in vocales:
    print(f"{vocal}: {palabra.count(vocal)}")


a: 0
e: 1
i: 0
o: 1
u: 0


Ejercicio 10

In [ ]:
# grabar
import numpy as np
precios = [50, 75, 46, 22, 80, 65, 8]
np.save("ejercicios/ejercicio_10.npy", np.array(precios))


In [ ]:
# cargar
import numpy as np
precios = np.load("ejercicios/ejercicio_10.npy")

print("Menor precio:", min(precios))
print("Mayor precio:", max(precios))


Menor precio: 8
Mayor precio: 80


Ejercicio 11

In [ ]:
# grabar
import numpy as np
vector1 = [1, 2, 3]
vector2 = [-1, 0, 2]
np.save("ejercicios/ejercicio_11_vector1.npy", np.array(vector1))
np.save("ejercicios/ejercicio_11_vector2.npy", np.array(vector2))


In [ ]:
#  cargar
import numpy as np
vector1 = np.load("ejercicios/ejercicio_11_vector1.npy")
vector2 = np.load("ejercicios/ejercicio_11_vector2.npy")

producto_escalar = np.dot(vector1, vector2)

print("Producto escalar:", producto_escalar)


Producto escalar: 5


Ejercicio 12

In [ ]:
# grabar
import numpy as np
matriz1 = [[1, 2], [3, 4]]
matriz2 = [[5, 6], [7, 8]]
np.save("ejercicios/ejercicio_12_matriz1.npy", np.array(matriz1))
np.save("ejercicios/ejercicio_12_matriz2.npy", np.array(matriz2))


In [ ]:
#  cargar
import numpy as np
matriz1 = np.load("ejercicios/ejercicio_12_matriz1.npy")
matriz2 = np.load("ejercicios/ejercicio_12_matriz2.npy")
producto = np.dot(matriz1, matriz2)

print("Producto de las matrices:")
print(producto)


Producto de las matrices:
[[19 22]
 [43 50]]


Ejercicio 13

In [ ]:
# grabar
import numpy as np
entrada = input("Introduce números separados por comas: ")
numeros = [float(x.strip()) for x in entrada.split(",")]
np.save("ejercicios/ejercicio_13.npy", np.array(numeros, dtype=float))


Introduce números separados por comas: 1,2,4


In [ ]:
# cargar
import numpy as np
numeros = np.load("ejercicios/ejercicio_13.npy")
media = np.mean(numeros)
desviacion = np.std(numeros)

print("Media:", round(media, 2))
print("Desviación típica:", round(desviacion, 2))


Media: 2.33
Desviación típica: 1.25


Tipos de datos

In [ ]:
#Enteros
np.int64

numpy.int64

In [ ]:
#Decimal, Flotantes
np.float64

numpy.float64

In [ ]:
#Complejos
np.complex64

numpy.complex64

In [ ]:
#Boleanos
np-np.bool_

Ejercicios propuestos 2

Ejercicio 1

In [1]:
año_inicio = int(input("Ingrese el año de inicio: "))
año_fin = int(input("Ingrese el año final: "))

años = list(range(año_inicio, año_fin + 1))
ventas = []

for año in años:
    venta = float(input(f"Ingrese las ventas para el año {año}: "))
    ventas.append(venta)

serie_ventas = pd.Series(ventas, index=años)
print("\nVentas originales:")
print(serie_ventas)

ventas_descuento = serie_ventas * 0.9
print("\nVentas con 10% de descuento:")
print(ventas_descuento)


Ingrese el año de inicio: 2023
Ingrese el año final: 2025
Ingrese las ventas para el año 2023: 2000
Ingrese las ventas para el año 2024: 11
Ingrese las ventas para el año 2025: 150

Ventas originales:
2023    2000.0
2024      11.0
2025     150.0
dtype: float64

Ventas con 10% de descuento:
2023    1800.0
2024       9.9
2025     135.0
dtype: float64


Ejercicio 2

In [2]:
def resumen_notas(diccionario_notas):
    notas = pd.Series(list(diccionario_notas.values()))
    resumen = pd.Series({
        'Nota mínima': notas.min(),
        'Nota máxima': notas.max(),
        'Nota media': notas.mean(),
        'Desviación típica': notas.std()
    })
    return resumen

notas_alumnos = {
    'Juan': 15,
    'Ana': 18,
    'Luis': 12,
    'Carla': 19,
    'Pedro': 14
}

print(resumen_notas(notas_alumnos))


Nota mínima          12.000000
Nota máxima          19.000000
Nota media           15.600000
Desviación típica     2.880972
dtype: float64


Ejercicio 3

In [6]:
def notas_aprobados(diccionario_notas):
    notas = pd.Series(diccionario_notas)
    aprobados = notas[notas >= 13].sort_values(ascending=False)
    return aprobados

notas_alumnos = {
    'Juan': 15,
    'Ana': 18,
    'Luis': 12,
    'Carla': 19,
    'Pedro': 14
}

print(notas_aprobados(notas_alumnos))


Carla    19
Ana      18
Juan     15
Pedro    14
dtype: int64


Ejercicio 4

In [7]:
datos = {
    'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril'],
    'Ventas': [30500, 35600, 28300, 33900],
    'Gastos': [22000, 23400, 18100, 20700]
}

df = pd.DataFrame(datos)
print(df)


       Mes  Ventas  Gastos
0    Enero   30500   22000
1  Febrero   35600   23400
2    Marzo   28300   18100
3    Abril   33900   20700


Ejercicio 5

In [8]:
def balance_total(df, lista_meses):
    df_filtrado = df[df['Mes'].isin(lista_meses)]
    balance = (df_filtrado['Ventas'] - df_filtrado['Gastos']).sum()
    return balance

meses_seleccionados = ['Enero', 'Marzo']
print(balance_total(df, meses_seleccionados))


18700


Ejercicio 6

In [17]:
def resumen_cotizacion(nombre_archivo):
    df = pd.read_csv(nombre_archivo)
    resumen = df.describe().loc[['min', 'max', 'mean']]
    resumen.rename(index={'min': 'Mínimo', 'max': 'Máximo', 'mean': 'Media'}, inplace=True)
    return resumen

Ejercicio 7

In [19]:
import pandas as pd

df = pd.read_csv('/content/titanic.csv')

print("Dimensiones:", df.shape)
print("Número de datos:", df.size)
print("Columnas:", df.columns.tolist())
print("Índices:", df.index.tolist())
print("Tipos de datos:\n", df.dtypes)
print("Primeras 10 filas:\n", df.head(10))
print("Últimas 10 filas:\n", df.tail(10))
print("Pasajero con ID 148:\n", df.loc[148])
print("Filas pares:\n", df.iloc[::2])
primera_clase = df[df['Pclass'] == 1]['Name'].sort_values()
print("Personas en primera clase ordenadas alfabéticamente:\n", primera_clase)
supervivientes = df['Survived'].value_counts(normalize=True) * 100
print("Porcentaje de personas que sobrevivieron y murieron:\n", supervivientes)
supervivientes_clase = df.groupby('Pclass')['Survived'].mean() * 100
print("Porcentaje de supervivientes en cada clase:\n", supervivientes_clase)
df = df.dropna(subset=['Age'])
edad_media_mujeres = df[df['Sex'] == 'female'].groupby('Pclass')['Age'].mean()
print("Edad media de mujeres por clase:\n", edad_media_mujeres)
df['MenorEdad'] = df['Age'] < 18
supervivencia_menores = df.groupby(['Pclass', 'MenorEdad'])['Survived'].mean() * 100
print("Porcentaje de menores y mayores que sobrevivieron en cada clase:\n", supervivencia_menores)

Dimensiones: (891, 12)
Número de datos: 10692
Columnas: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
Índices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 18

ejercicio 8

In [35]:
df = pd.read_csv('misDatos.csv')

columnas_actuales = df.columns.tolist()

columnas_fijas = [col for col in ['ESTACION', 'MAGNITUD', 'AÑO', 'MES'] if col in columnas_actuales]
columnas_dias = [col for col in columnas_actuales if col.startswith('D')]

df_filtrado = df[columnas_fijas + columnas_dias]

if 'DIA' not in df_filtrado.columns:
    df_filtrado = df_filtrado.melt(id_vars=columnas_fijas, var_name='DIA', value_name='VALOR')
    df_filtrado['DIA'] = df_filtrado['DIA'].str.extract('D(\d+)').astype(int, errors='ignore')

if all(col in df_filtrado.columns for col in ['AÑO', 'MES', 'DIA']):
    df_filtrado['FECHA'] = pd.to_datetime(df_filtrado[['AÑO', 'MES', 'DIA']], errors='coerce')
    df_filtrado = df_filtrado[~df_filtrado['FECHA'].isna()]
    df_filtrado = df_filtrado.sort_values(['ESTACION', 'MAGNITUD', 'FECHA'])

print(df_filtrado.head())




Empty DataFrame
Columns: [DIA, VALOR]
Index: []
