<a href="https://colab.research.google.com/github/Anthonylwz/cssma/blob/main/Examen_Final_de_fundamentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Parte 1: Fundamentos NumPy


Crea un arreglo NumPy de dimensión 1 con los números del 1 al 20

In [20]:
import numpy as np

array_1d = np.arange(1, 21)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Selecciona los múltiplos de 3 de ese arreglo y muéstralos

In [21]:
multiples_of_3 = array_1d[array_1d % 3 == 0]
print(multiples_of_3)

[ 3  6  9 12 15 18]


Genera una matriz aleatoria de tamaño 5x5 con números entre 0 y 1

In [22]:
random_matrix = np.random.rand(5, 5)
print(random_matrix)

[[0.2882297  0.53142009 0.04549897 0.91193188 0.46095267]
 [0.07041392 0.33475551 0.97108144 0.90822337 0.18792963]
 [0.28663728 0.28073086 0.64675846 0.34549393 0.70445783]
 [0.60994302 0.49118925 0.00647889 0.45072819 0.24957279]
 [0.79421539 0.22985966 0.60745953 0.62707852 0.92103596]]


Calcula la media, la desviación estándar y el valor máximo de esa matriz.

In [23]:
mean_value = np.mean(random_matrix)
std_dev = np.std(random_matrix)
max_value = np.max(random_matrix)

print(f"Media: {mean_value}")
print(f"Desviación estándar: {std_dev}")
print(f"Valor máximo: {max_value}")

Media: 0.4784830690407938
Desviación estándar: 0.2811431540126046
Valor máximo: 0.9710814358872997


Transforma la matriz en un vector de una sola dimensión

In [24]:
vector_1d = random_matrix.flatten()
print(vector_1d)

[0.2882297  0.53142009 0.04549897 0.91193188 0.46095267 0.07041392
 0.33475551 0.97108144 0.90822337 0.18792963 0.28663728 0.28073086
 0.64675846 0.34549393 0.70445783 0.60994302 0.49118925 0.00647889
 0.45072819 0.24957279 0.79421539 0.22985966 0.60745953 0.62707852
 0.92103596]


Parte 2: Fundamentos Pandas

Crea un DataFrame con los siguientes datos de estudiantes:
Nombre Edad Nota_Matemáticas Nota_IA
Ana 20 18 17
Luis 21 15 14
María 19 16 18
Pedro 22 12 13
Sofía 20 19 20

In [25]:
import pandas as pd

data = {'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'],
        'Edad': [20, 21, 19, 22, 20],
        'Nota_Matemáticas': [18, 15, 16, 12, 19],
        'Nota_IA': [17, 14, 18, 13, 20]}

df_students = pd.DataFrame(data)
display(df_students)

Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20

Calcula el promedio de cada columna numérica.

In [26]:
average_scores = df_students[['Edad', 'Nota_Matemáticas', 'Nota_IA']].mean()
print("Promedio de cada columna numérica:")
print(average_scores)

Promedio de cada columna numérica:
Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64


Filtra los estudiantes con nota de IA mayor a 15

In [27]:
students_ia_greater_than_15 = df_students[df_students['Nota_IA'] > 15]
display(students_ia_greater_than_15)

Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20

Agrega una nueva columna llamada Promedio que contenga el promedio de
Nota_Matemáticas y Nota_IA.

In [28]:
df_students['Promedio'] = (df_students['Nota_Matemáticas'] + df_students['Nota_IA']) / 2
display(df_students)

Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5

Ordena el DataFrame según la columna Promedio de mayor a menor.

In [29]:
df_students_sorted = df_students.sort_values(by='Promedio', ascending=False)
display(df_students_sorted)

Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5

Parte 3: Algoritmia aplicada

Escribe una función en Python que reciba una lista de números y devuelva:
o El número mayor
o El número menor
o El promedio

In [30]:
def analyze_list(numbers):
  """
  Analiza una lista de números y devuelve: el mayor, el menor y el promedio.

  Args:
    numbers: Una lista de números.

  Returns:
    Una tupla que contiene el número mayor, el número menor y el promedio.
  """
  if not numbers:
    return None, None, None

  largest = max(numbers)
  smallest = min(numbers)
  average = sum(numbers) / len(numbers)

  return largest, smallest, average

my_list = [10, 5, 20, 15, 25]
largest_num, smallest_num, avg_num = analyze_list(my_list)

print(f"Número mayor: {largest_num}")
print(f"Número menor: {smallest_num}")
print(f"Promedio: {avg_num}")

Número mayor: 25
Número menor: 5
Promedio: 15.0


Usando NumPy, implementa una función de activación Sigmoide definida como:
f(x)=11+e−xf(x) = \frac{1}{1 + e^{-x}}f(x)=1+e−x1
Aplica la función a un arreglo x = np.array([-2, -1, 0, 1, 2])

In [31]:
import numpy as np

def sigmoid(x):
  """
  Implementa la función de activación Sigmoide.

  Args:
    x: Un arreglo NumPy.

  Returns:
    El arreglo con la función Sigmoide aplicada elemento a elemento.
  """
  return 1 / (1 + np.exp(-x))

x = np.array([-2, -1, 0, 1, 2])

sigmoid_output = sigmoid(x)

print("Arreglo de entrada:", x)
print("Salida de la función Sigmoide:", sigmoid_output)

Arreglo de entrada: [-2 -1  0  1  2]
Salida de la función Sigmoide: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


Crea una función que clasifique a los estudiantes del DataFrame en "Aprobado"
si su Promedio ≥ 14, y "Desaprobado" en caso contrario. Añade una nueva
columna llamada Estado.

In [32]:
def classify_student(promedio):
  """
  Clasifica a un estudiante como "Aprobado" o "Desaprobado" basado en su promedio.

  Args:
    promedio: El promedio del estudiante.

  Returns:
    "Aprobado" si el promedio es mayor o igual a 14, de lo contrario "Desaprobado".
  """
  if promedio >= 14:
    return "Aprobado"
  else:
    return "Desaprobado"

df_students['Estado'] = df_students['Promedio'].apply(classify_student)

display(df_students)

Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado

Agrega una nueva columna llamada Crecimiento que calcule el porcentaje de
crecimiento entre Ventas_2024 y Ventas_2025.

In [33]:

datos = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}

df = pd.DataFrame(datos)

df['Crecimiento'] = ((df['Ventas_2025'] - df['Ventas_2024']) / df['Ventas_2024']) * 100

print(df)


  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          120          200    66.666667
1        B          340          400    17.647059
2        C          560          600     7.142857
3        D          230          300    30.434783
4        E          150          180    20.000000


Identifica el producto con mayor crecimiento y muéstralo.


In [34]:
producto_top = df.loc[df['Crecimiento'].idxmax()]

print(" El producto con mayor crecimiento es:")
print(producto_top)


 El producto con mayor crecimiento es:
Producto               A
Ventas_2024          120
Ventas_2025          200
Crecimiento    66.666667
Name: 0, dtype: object


Parte 5: Resolución de ecuaciones

Ecuación de primer grado
o Implementa una función en Python que resuelva una ecuación de la forma:
ax+b=0ax + b = 0ax+b=0
por ejemplo: 2x + 4 = 0.
o La función debe retornar el valor de x.

In [39]:
import numpy as np

# Ejercicio 1
# Ecuación: 2x + 4 = 0
# Se representa como sistema: [2] * x = -4
A = np.array([[2]])
B = np.array([-4])

sol = np.linalg.solve(A, B)
print("Ejercicio 1 solución (x):", sol)


Ejercicio 1 solución (x): [-2.]


Ecuación de segundo grado
o Implementa una función en Python que resuelva una ecuación de la forma:
ax2+bx+c=0ax^2 + bx + c = 0ax2+bx+c=0
usando la fórmula general:
x=−b±b2−4ac2ax = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}x=2a−b±b2−4ac
o La función debe retornar las dos soluciones (reales o complejas).

In [40]:
import numpy as np

# Ejercicio 2
# Ecuación: x^2 + 5x + 6 = 0
a, b, c = 1, 5, 6

# Fórmula general
discriminante = b**2 - 4*a*c
x1 = (-b + np.sqrt(discriminante)) / (2*a)
x2 = (-b - np.sqrt(discriminante)) / (2*a)

print("Ejercicio 2 soluciones (x1, x2):", (x1, x2))


Ejercicio 2 soluciones (x1, x2): (np.float64(-2.0), np.float64(-3.0))
